server:
  port: 8003
spring:
  application:
    name: snut-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: localhost:2181

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.snut.payment.entities

