server:
  port: 7003

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka7003.com #eureka服务短的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要取检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  server:
    #关闭自我保护机制，保证补课用的服务被及时清除掉
    enable-self-preservation: false
    #默认刷新时间2秒
    eviction-interval-timer-in-ms: 2000