server:
  port: 80

spring:
  application:
    name: snut-order-server

eureka:
  client:
    #表示将自己注册进EurekaServer
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息。单节点无所谓，集群必须设置为ture才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

